{ lib
, runCommand
, R
, rEnvironment ? []
, reticulatePython ? null
, sourceProfile ? "~/.Rprofile"
}: let
  script = ''
    mkdir $out
    p=$out/.Rprofile
  '' + (lib.optionalString (sourceProfile != null) ''
    echo    'another_profile <- ${lib.strings.escapeNixString sourceProfile}' >> $p
    echo    'if (file.exists(another_profile)) {' >> $p
    echo    '  source(another_profile)' >> $p
    echo    '} else {' >> $p
    echo    '  cat("File ${sourceProfile} does not exists. Skipping sourcing.\n")' >> $p
    echo    '}' >> $p
  '') + ''
    # push default R packages location into the end
    echo    'Sys.setenv(R_LIBS_USER = "")' >> $p

    # set libraries
    echo    '# Autogenerated by setup from R_LIBS_SITE' >> $p

    echo -n '.libPaths(c("' >> $p
    echo -n $R_LIBS_SITE | sed -e 's/:/", "/g' >> $p
    echo    '", .libPaths()))' >> $p

  '' + (lib.optionalString (reticulatePython != null) ''
    # set python
    echo   'Sys.setenv(RETICULATE_PYTHON = "${reticulatePython}/bin/python")' >> $p
  '');
in runCommand "Rprofile" {
  buildInputs = [ R ] ++ rEnvironment;
} script
